version: "3"
services:
  task-tracker-api:
    image: $IMAGE_TAG_SERVER
    build: ./api
    environment:
      - API_PORT=8080
      - API_HOST=http://task-tracker-api
      - DBDATABASE=data
      - DBHOST=mariadb
      - DBPASSWORD=password
      - DBPORT=3306
      - DBUSER=user
      - NODE_ENV=local
    depends_on:
      - db

  db:
    image: mariadb:latest
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      - ./.env

  nginx:
    image: $IMAGE_TAG_NGINX
    depends_on:
      - task-tracker-api

  cypress:
    command: /bin/bash -c "npm install && npm run cypress"
    image: $IMAGE_TAG_CYPRESS
    environment:
      - CYPRESS_baseUrl=http://nginx:8080
