version: '3.8'

services:
  mariadb:
      image: mariadb:latest
      volumes:
        - data:/var/lib/mysql
      restart: always
      env_file:
          - .env

  backend:
      ##restart: always
      image: node:14
      working_dir: /usr/src/app
      volumes:
        - ./app:/usr/src/app
      environment: 
          - PORT=3000
      depends_on:
          - mariadb
      ports:
          - "3000:3000"
      env_file:
          - .env
      command: /bin/bash -c "npm install && npm run start"

volumes:
  data: